# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8579dd3f-1e8e-4c8a-812f-d271bc2c89fc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8579dd3f-1e8e-4c8a-812f-d271bc2c89fc".device = "/dev/disk/by-uuid/8579dd3f-1e8e-4c8a-812f-d271bc2c89fc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/58B8-1B29";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
